*&---------------------------------------------------------------------*
*& Include          YRTEST001T
*&---------------------------------------------------------------------*


CONSTANTS :C_HANDLE_NODE_DOUBLE_CLICK     TYPE C LENGTH 50 VALUE 'HANDLE_NODE_DOUBLE_CLICK',
           C_HANDLE_CHECKBOX_CHANGE       TYPE C LENGTH 50 VALUE 'HANDLE_CHECKBOX_CHANGE',
           C_HANDLE_EXPAND_NC             TYPE C LENGTH 50 VALUE 'HANDLE_EXPAND_NC',
           C_HANDLE_HEADER_CLICK          TYPE C LENGTH 50 VALUE 'HANDLE_HEADER_CLICK',
           C_HANDLE_ITEM_CONTEXT_MENU_RQ  TYPE C LENGTH 50 VALUE 'HANDLE_ITEM_CONTEXT_MENU_RQ',
           C_HANDLE_ITEM_CONTEXT_MENU_SEL TYPE C LENGTH 50 VALUE 'HANDLE_ITEM_CONTEXT_MENU_SEL',
           C_HANDLE_ITEM_KEYPRESS         TYPE C LENGTH 50 VALUE 'HANDLE_ITEM_KEYPRESS',
           C_HANDLE_LINK_CLICK            TYPE C LENGTH 50 VALUE 'HANDLE_LINK_CLICK',
           C_HANDLE_NODE_CONTEXT_MENU_RQ  TYPE C LENGTH 50 VALUE 'HANDLE_NODE_CONTEXT_MENU_RQ',
           C_HANDLE_NODE_CONTEXT_MENU_SEL TYPE C LENGTH 50 VALUE 'HANDLE_NODE_CONTEXT_MENU_SEL',
           C_HANDLE_NODE_KEYPRESS         TYPE C LENGTH 50 VALUE 'HANDLE_NODE_KEYPRESS',
           C_HANDLE_ON_DRAG               TYPE C LENGTH 50 VALUE 'HANDLE_ON_DRAG',
           C_HANDLE_ON_DRAG_MULTIPLE      TYPE C LENGTH 50 VALUE 'HANDLE_ON_DRAG_MULTIPLE',
           C_HANDLE_ON_DROP               TYPE C LENGTH 50 VALUE 'HANDLE_ON_DROP',
           C_HANDLE_ON_DROP_COMPLETE      TYPE C LENGTH 50 VALUE 'HANDLE_ON_DROP_COMPLETE',
           C_HANDLE_ON_DROP_EXTERNAL      TYPE C LENGTH 50 VALUE 'HANDLE_ON_DROP_EXTERNAL_FILES',
           C_HANDLE_ON_DROP_GET_FLAVOR    TYPE C LENGTH 50 VALUE 'HANDLE_ON_DROP_GET_FLAVOR',
           C_HANDLE_SELECTION_CHANGED     TYPE C LENGTH 50 VALUE 'HANDLE_SELECTION_CHANGED',
           C_HANDLE_ON_DROP_COMPLETE_MULT TYPE C LENGTH 50 VALUE 'HANDLE_ON_DROP_COMPLETE_MULT',
           C_HANDLE_DATA_CHANGED          TYPE C LENGTH 50 VALUE 'HANDLE_DATA_CHANGED',
           C_HANDLE_DATA_CHANGED_FINISHED TYPE C LENGTH 50 VALUE 'HANDLE_DATA_CHANGED_FINISHED',
           C_HANDLE_DOUBLE_CLICK          TYPE C LENGTH 50 VALUE 'HANDLE_DOUBLE_CLICK',
           C_HANDLE_DROP_EXTERNAL_FILES   TYPE C LENGTH 50 VALUE 'HANDLE_DROP_EXTERNAL_FILES',
           C_HANDLE_HOTSPOT_CLICK         TYPE C LENGTH 50 VALUE 'HANDLE_HOTSPOT_CLICK',
           C_HANDLE_ONDRAG                TYPE C LENGTH 50 VALUE 'HANDLE_ONDRAG',
           C_HANDLE_ONDROPCOMPLETE        TYPE C LENGTH 50 VALUE 'HANDLE_ONDROPCOMPLETE',
           C_HANDLE_ONF4                  TYPE C LENGTH 50 VALUE 'HANDLE_ONF4',
           C_HANDLE_TOOLBAR               TYPE C LENGTH 50 VALUE 'HANDLE_TOOLBAR',
           C_HANDLE_TOP_OF_PAGE           TYPE C LENGTH 50 VALUE 'HANDLE_TOP_OF_PAGE',
           C_HANDLE_USER_COMMAND          TYPE C LENGTH 50 VALUE 'HANDLE_USER_COMMAND'.

TYPES : BEGIN OF ty_list,
       ebeln TYPE ebeln,
       ebelp TYPE ebelp,
       bsart TYPE bsart,
       lifnr TYPE lifnr,
       menge TYPE menge_d,
       meins TYPE meins,
       netpr TYPE netpr,
       cellstyl TYPE lvc_t_styl,
       cellscol TYPE lvc_t_scol,
        END OF ty_list,
        TT_LIST TYPE TABLE OF TY_LIST WITH EMPTY KEY.

TYPES : BEGIN OF ty_header,
          ebeln TYPE ebeln,
          ebelp TYPE ebelp,
          bsart TYPE bsart,
        END OF ty_header.

TYPES : BEGIN OF ty_node,
          ebeln TYPE ebeln,
          ebelp TYPE ebelp,
          node_key TYPE LVC_NKEY,
        END OF ty_node.


*DATA: LV_001 TYPE C LENGTH 15 VALUE 'Screen 100'.
