*&---------------------------------------------------------------------*
*& Include          YRTEST001S
*&---------------------------------------------------------------------*


SELECTION-SCREEN BEGIN OF BLOCK b01.
  SELECTION-SCREEN BEGIN OF LINE.
  PARAMETERS : p_01 RADIOBUTTON GROUP g01 DEFAULT 'X' USER-COMMAND m01.
  SELECTION-SCREEN COMMENT (15) LV_001 FOR FIELD P_01.
  PARAMETERS : p_02 RADIOBUTTON GROUP g01.
  SELECTION-SCREEN COMMENT (15) LV_002 FOR FIELD P_02.
*  PARAMETERS : p_03 RADIOBUTTON GROUP g01.
*  SELECTION-SCREEN COMMENT (15) LV_003 FOR FIELD P_03.
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK b01.
