************************************************************************
* SOURCE OF TRUTH — Procedural main-program template.
*
* Every Procedural ABAP program generated by sc4sap (e.g., via
* /sc4sap:create-program) MUST mirror this file exactly — header comment
* block, INCLUDE order, event-block layout, and the 6 header fields below.
* Deviations require a written justification in spec.md and are a MAJOR
* finding in Phase 6 review.
*
* Canonical structure:
*   1. REPORT statement preceded by the 6-field header comment block
*      (Program / Author / Date / S/4HANA / Version / Desc).
*   2. INCLUDE statements in order: t, s, c, a, o, i, f
*      (NEVER `e` — `e` is OOP-only for LCL_EVENT).
*   3. Event blocks in Main body: INITIALIZATION, AT SELECTION-SCREEN
*      variants, START-OF-SELECTION, END-OF-SELECTION — each delegates
*      to a FORM via PERFORM.
*
* Companion rules: common/include-structure.md (activation protocol,
* anti-patterns) and common/clean-code-procedural.md (mandatory header
* format, Screen/GUI/Text completion protocols).
************************************************************************
*&---------------------------------------------------------------------*
*&  Module      : SD Module
*&  Program ID  : ZSDR23070
*&  Tcode       : ZSDR23070
*&  Title       : Sales Order Status List
*&  Description : Warehouse sales order list w/ status
*&---------------------------------------------------------------------*
*&  Change History
*&---------------------------------------------------------------------*
*& Change No   |  Changed by  |  Change Date
*& CH-001      |  SVT_000005  |  2026-01-12
*& Description : Initialization
*&---------------------------------------------------------------------*
REPORT  zsdr23070
        NO STANDARD PAGE HEADING
        MESSAGE-ID zsd11.

*&---------------------------------------------------------------------*
* Program Define - Program Top Include
*&---------------------------------------------------------------------*
INCLUDE zsdr23070t.

*&---------------------------------------------------------------------*
* ALV GRID CLASS INCLUDE - Default Include
*&---------------------------------------------------------------------*
INCLUDE zsdr23070c.

*&---------------------------------------------------------------------*
* Program Define - Selection Screen & Select-Option
*&---------------------------------------------------------------------*
INCLUDE zsdr23070s.

*&---------------------------------------------------------------------*
* Program Define - Screen PBO
*&---------------------------------------------------------------------*
INCLUDE zsdr23070o.

*&---------------------------------------------------------------------*
* Program Define - Screen PAI
*&---------------------------------------------------------------------*
INCLUDE zsdr23070i.

*&---------------------------------------------------------------------*
* for ALV Grid
*&---------------------------------------------------------------------*
INCLUDE zsdr23070a.

*&---------------------------------------------------------------------*
* Program Define - Business Logic Form
*&---------------------------------------------------------------------*
INCLUDE zsdr23070f.

*----------------------------------------------------------------------*
* AT SELECTION-SCREEN
*----------------------------------------------------------------------*
AT SELECTION-SCREEN.
  PERFORM check_common_authority.

  PERFORM check_screen_input.

AT SELECTION-SCREEN OUTPUT.
  PERFORM set_screen_output.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_var.
  PERFORM set_screen_variant.

*----------------------------------------------------------------------*
* INITIALIZATION
*----------------------------------------------------------------------*
INITIALIZATION.
  PERFORM set_screen.

*----------------------------------------------------------------------*
* START-OF-SELECTION
*----------------------------------------------------------------------*
START-OF-SELECTION.
  PERFORM start_of_selection.

*----------------------------------------------------------------------*
* END-OF-SELECTION
*----------------------------------------------------------------------*
END-OF-SELECTION.
  IF p_bat = 'X'.
    PERFORM batch_data_collection.
  ELSE.
    PERFORM end_of_selection.
  ENDIF.