************************************************************************
* SOURCE OF TRUTH — Procedural main-program template.
*
* Every Procedural ABAP program generated by sc4sap (e.g., via
* /sc4sap:create-program) MUST mirror this file exactly — header comment
* block, INCLUDE order, event-block layout, and the 6 header fields below.
* Deviations require a written justification in spec.md and are a MAJOR
* finding in Phase 6 review.
*
* Canonical structure:
*   1. REPORT statement preceded by the 6-field header comment block
*      (Program / Author / Date / S/4HANA / Version / Desc).
*   2. INCLUDE statements in order: t, s, c, a, o, i, f
*      (NEVER `e` — `e` is OOP-only for LCL_EVENT).
*   3. Event blocks in Main body: INITIALIZATION, AT SELECTION-SCREEN
*      variants, START-OF-SELECTION, END-OF-SELECTION — each delegates
*      to a FORM via PERFORM.
*
* Companion rules: common/include-structure.md (activation protocol,
* anti-patterns) and common/clean-code-procedural.md (mandatory header
* format, Screen/GUI/Text completion protocols).
************************************************************************
*&---------------------------------------------------------------------*
*& Sample Report Program Template
*& Program  : ZRSC4SAP_PRC_EX
*& Author   : SVT_00005
*& Date     : 2026-04-03
*& S/4HANA  : 2025 Release
*& Version  : v1.0 - Include Structure Change Completed
*& Desc     : Sample Report Program Template
*&
*&
*&---------------------------------------------------------------------*
REPORT ZRSC4SAP_PRC_EX.

INCLUDE ZRSC4SAP_PRC_EXT. "TOP   — declare `DATA: gv_okcode TYPE sy-ucomm.` here
INCLUDE ZRSC4SAP_PRC_EXS. "SELECTION SCREEN
INCLUDE ZRSC4SAP_PRC_EXC. "CLASS
INCLUDE ZRSC4SAP_PRC_EXA. "ALV
INCLUDE ZRSC4SAP_PRC_EXO. "PBO
INCLUDE ZRSC4SAP_PRC_EXI. "PAI
INCLUDE ZRSC4SAP_PRC_EXF. "FORM

*&---------------------------------------------------------------------*
*& INITIALIZATION
*&---------------------------------------------------------------------*
INITIALIZATION.

*&---------------------------------------------------------------------*
*& AT SELECTION-SCREEN
*&---------------------------------------------------------------------*
AT SELECTION-SCREEN.

*&---------------------------------------------------------------------*
*& AT SELECTION-SCREEN OUTPUT 
*&---------------------------------------------------------------------*
AT SELECTION-SCREEN OUTPUT.

*&---------------------------------------------------------------------*
*& AT SELECTION-SCREEN
*&---------------------------------------------------------------------*
AT SELECTION-SCREEN OUTPUT FOR FIELD P_FILE.

    PERFROM GET_FILE.

*&---------------------------------------------------------------------*
*& START-OF-SELECTION
*&---------------------------------------------------------------------*
START-OF-SELECTION.

    PERFORM GET_DATA.

*&---------------------------------------------------------------------*
*& END-OF-SELECTION
*&---------------------------------------------------------------------*
END-OF-SELECTION.

    PERFORM DISPLAY.